# -*- coding: utf-8 -*-
"""Import CHIP data ADD question vars

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QJfuDEQD459xx0cnz9swztw6mC2S2ERN

# Script to import data from COVID States surveys
"""

import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

file_path_base = '/content/drive/MyDrive/0AAAAA_CHIP50/data/CSV/'

questions_list = []
question_variables = input("Type in question variables separated by commas: ")
questions_list = [x.strip() for x in question_variables.split(',')]

questions_list

questions_list.append('id')
questions_list.append('wave')

questions_list

if 'id' in questions_list:
  questions_list.remove('id')
questions_list.insert(0, 'id')
questions_list

## Function to run preprocessing on certain waves 
waves = input("Type in the waves separated by commas: ")
waves_list = [x.strip() for x in waves.split(',')]
# 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,35.1

waves_list

# prompt: write a function filter_df that takes a df and a vars_list as input, checks if the vars in vars_list exists in df, and for those vars that does exist, filter the df for them
def filter_df(df, questions_list):
  # Check if the variables in vars_list exist in the dataframe.
  existing_vars = [var for var in questions_list if var in df.columns]
  # Filter the dataframe for the existing variables.
  filtered_df = df[existing_vars]
  return filtered_df

# prompt: loop through the list_wave_number to create a new list wave_names that append 'CSP_W' before each number

waves_list_string = []
for number in waves_list:
  waves_list_string.append('CSP_W' + str(number))
waves_list_string

# prompt: create a list 30 of dataframes and read the file url
df_all_waves = []
for item in waves_list_string:
  file_path_string = file_path_base + item + '.csv'
  print(file_path_string) # Added this line to print the file path
  df = pd.read_csv(file_path_string, index_col=False, dtype='unicode')
  df_filtered = filter_df(df,questions_list)
  df_all_waves.append(df_filtered)
#df_all_waves

# concatenate all the waves into one big one 
df_all_waves_concat = pd.concat(df_all_waves, ignore_index=True)

df_all_waves_concat

# Dropping bad columns 
columns_to_check = [col for col in df_all_waves_concat.columns if col not in ['id', 'wave']]
df_all_waves_concat = df_all_waves_concat.dropna(subset=columns_to_check)

df_all_waves_concat

from datetime import datetime
# Get the current date and time
now = datetime.now()
# Format the current date and time into a string 'YYYY_MM_DD_time_HH_MM'
datetime_str = now.strftime("%Y_%m_%d_t_%H_%M")
# Print the generated date and time
print(datetime_str)

# prompt: export df_all_waves_concat to a csv file
filename = "EXPORT_CHIP50_question_vars_" + datetime_str

df_all_waves_concat.to_csv('/content/drive/MyDrive/CHIP50/exported_data/' + filename + ".csv", index=False)

df_quest_vars = df_all_waves_concat

df_quest_vars

"""# END"""

waves_list_with_values = df_all_waves_concat['wave'].unique().tolist()
waves_list_with_values

list_waves_numbers = waves_list_with_values

import gspread
from google.colab import auth
import google.auth # Added import for google.auth
from gspread_dataframe import get_as_dataframe

# Authenticate with Google Colab
auth.authenticate_user()

# Authorize gspread using the authenticated credentials
credentials, project = google.auth.default()
gc = gspread.authorize(credentials)

# Extract sheet_id and gid from the URL
sheet_url = 'https://docs.google.com/spreadsheets/d/1p3e6K39Sy7gzCy6uxgNs_8NbvmqrMmiY7ycG_Yvhb0A/edit?gid=577015518#gid=577015518'
sheet_id = sheet_url.split('/d/')[1].split('/edit')[0]
gid = sheet_url.split('gid=')[1].split('#')[0]

# Open the spreadsheet and select the worksheet
spreadsheet = gc.open_by_key(sheet_id)
worksheet = spreadsheet.get_worksheet_by_id(int(gid))

# Read the worksheet into a Pandas DataFrame
df = get_as_dataframe(worksheet)

print("Google Sheet loaded successfully into DataFrame 'df'.")
df

waves_list = []
for number in list_waves_numbers:
  waves_list.append('CSP_W' + str(number))
waves_list

sheet_id = '18Hm7W8wNRW9aPZkGti3LiQuEOZpTuNafLrN7V6h0I-g'
gid_demo_vars = '0'

# Construct CSV export URLs
url_demo_vars = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv&gid={gid_demo_vars}"

# Import Google Sheets as DataFrames
df_demo_vars = pd.read_csv(url_demo_vars)
demo_vars_List = df_demo_vars['demographic vars'].to_list()

all_vars_list = demo_vars_List
all_vars_list

# prompt: write a function filter_df that takes a df and a vars_list as input, checks if the vars in vars_list exists in df, and for those vars that does exist, filter the df for them
def filter_df(df, vars_list):
  # Check if the variables in vars_list exist in the dataframe.
  existing_vars = [var for var in vars_list if var in df.columns]
  # Filter the dataframe for the existing variables.
  filtered_df = df[existing_vars]
  return filtered_df

# prompt: create a list 30 of dataframes and read the file url
df_all_waves = []
for item in waves_list:
  file_path_string = file_path_base + item + '.csv'
  print(file_path_string) # Added this line to print the file path
  df = pd.read_csv(file_path_string, index_col=False, dtype='unicode')
  df_filtered = filter_df(df,all_vars_list)
  df_all_waves.append(df_filtered)
#df_all_waves

df_all_waves_concat_demovars = pd.concat(df_all_waves, ignore_index=True)

df_all_waves_concat_demovars

df_quest_vars

merged_df = pd.merge(df_all_waves_concat_demovars, df_quest_vars, on=['id', 'wave'], how='inner')
merged_df.head()

questions_list_string = ','.join(questions_list)
questions_list_underscore = questions_list_string.replace(',', '_')
questions_list_underscore = questions_list_underscore[2:-5]
print(questions_list_underscore)

from datetime import datetime
import pytz
utc_now = datetime.now(pytz.utc)
est = pytz.timezone('US/Eastern')
est_now = utc_now.astimezone(est)
current_time = est_now.strftime('%Y_%m_%d-%H_%M')
output_filename = f'CHIP50{questions_list_underscore}_{current_time}.csv'

merged_df.to_csv(output_filename, index=False)
print(f"DataFrame exported to {output_filename}")

from google.colab import files
files.download(output_filename)

merged_df.to_csv('/content/drive/MyDrive/CHIP50/exported_data/' + output_filename + ".csv", index=False)

output_filename

"""# END 2"""