"""
Survey question wording for each CHIP50 variable.

Sourced from the COVID States Project survey text archive
(https://github.com/kateto/COVID19/tree/master/SURVEYS), which publishes the
exact Qualtrics question wording and response options for every wave. For each
variable, the wording is taken from the most recent wave in which it was
fielded. Where a variable is one item in a matrix/multi-select question (e.g.
platform-specific trust or usage items, or pol_news1_N / pol_news2_N source
checkboxes), the stem question is combined with the item-specific label.
"""

QUESTION_WORDING: dict[str, str] = {
    # DEMOGRAPHIC_COLUMNS
    "age_cat_8": "Age range (8 categories)",
    "education_cat": "Education level (5 categories)",
    "income_cat_10": "What was the total combined income of your household for the past year?",
    "race_cat_5": "Race as provided by vendor (select one, 5 categories)",
    "gender": "Gender as provided by vendor (M/F only)",
    "party3": "Political party",
    "party7": "Political affiliation",
    "urban_type": "Urban type (NCHS)",
    "state": "State name Text entry:______________",
    "state_code": "Two-letter state code Text entry:______________",

    # PLATFORM_COLUMNS
    "use_facebook": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — Facebook",
    "use_instagram": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — Instagram",
    "use_youtube": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — YouTube",
    "use_twitter": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — X (Twitter)",
    "use_tiktok": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — TikTok",
    "use_snapchat": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — Snapchat",
    "use_linkedin": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — LinkedIn",
    "use_reddit": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — Reddit",
    "use_whatsapp": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — WhatsApp",
    "use_messenger": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — Facebook Messenger",
    "use_pinterest": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — Pinterest",
    "use_tumblr": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — Tumblr",
    "use_gab": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — Gab",
    "use_parler": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — Parler",
    "use_4chan": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — 4chan",
    "use_truth": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — Truth Social",
    "use_mastodon": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — Mastodon",
    "use_post": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — Post",
    "use_threads": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — Threads",
    "use_bluesky": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — Bluesky",

    # ATTITUDINAL_COLUMNS
    "ideology": "In general, do you think of yourself as...",
    "economy": "How would you rate economic conditions in this country today?",
    "voted20": "Which candidate did you vote for in the 2020 U.S. presidential election? - Selected Choice",
    "voted24": "Which candidate did you vote for in the 2024 U.S. presidential election? - Selected Choice",
    "trump_win": "How much do you agree or disagree with the following statement: “If votes were fairly counted, Donald Trump would have won the 2020 election”",
    "conspiracy_1": "Even though we live in a democracy, a few people will always run things anyway.",
    "conspiracy_2": "The people who really 'run' the country are not known to the voters",
    "conspiracy_3": "Big events like wars, recessions, and the outcomes of elections are controlled by small groups of people who are working in secret against the rest of us.",
    "conspiracy_4": "Much of our lives are being controlled by plots hatched in secret places",
    "pol_info": "How closely do you follow news and information about politics and current affairs?",
    "pol_disc": "How often do you talk to people about politics and current affairs, either in person, over the phone, or electronically?",
    "trump_gen": "Do you approve or disapprove of the way Donald Trump is handling his job as president?",
    "age": "Respondent age (in years)",

    # FREQ_COLUMNS
    "freq_facebook": "How often do you use the following social media platforms? - Facebook",
    "freq_instagram": "How often do you use the following social media platforms? - Instagram",
    "freq_youtube": "How often do you use the following social media platforms? - YouTube",
    "freq_twitter": "How often do you use the following social media platforms? - X (Twitter)",
    "freq_tiktok": "How often do you use the following social media platforms? - TikTok",
    "freq_snapchat": "How often do you use the following social media platforms? - Snapchat",
    "freq_linkedin": "How often do you use the following social media platforms? - LinkedIn",
    "freq_reddit": "How often do you use the following social media platforms? - Reddit",
    "freq_whatsapp": "How often do you use the following social media platforms? - WhatsApp",
    "freq_messenger": "How often do you use the following social media platforms? - Facebook Messenger",
    "freq_pinterest": "How often do you use the following social media platforms? - Pinterest",
    "freq_tumblr": "How often do you use the following social media platforms? - Tumblr",
    "freq_gab": "How often do you use the following social media platforms? - Gab",
    "freq_parler": "How often do you use the following social media platforms? - Parler",
    "freq_4chan": "How often do you use the following social media platforms? - 4chan",
    "freq_truth": "How often do you use the following social media platforms? - Truth Social",
    "freq_mastodon": "How often do you use the following social media platforms? - Mastodon",
    "freq_post": "How often do you use the following social media platforms? - Post",
    "freq_threads": "How often do you use the following social media platforms? - Threads",
    "freq_bluesky": "How often do you use the following social media platforms? - Bluesky",

    # TRUST_COLUMNS
    "sm_trust_youtube": "How much do you trust news or information you see on… - YouTube",
    "sm_trust_facebook": "How much do you trust news or information you see on… - Facebook",
    "sm_trust_twitter": "How much do you trust news or information you see on… - X (Twitter)",
    "sm_trust_instagram": "How much do you trust news or information you see on… - Instagram",
    "sm_trust_reddit": "How much do you trust news or information you see on… - Reddit",
    "sm_trust_tiktok": "How much do you trust news or information you see on… - TikTok",
    "sm_trust_whatsapp": "How much do you trust news or information you see on… - WhatsApp",
    "sm_trust_linkedin": "How much do you trust news or information you see on… - LinkedIn",
    "sm_trust_truth": "How much do you trust news or information you see on… - Truth Social",
    "sm_trust_parler": "How much do you trust news or information you see on… - Parler",
    "sm_trust_mastodon": "How much do you trust news or information you see on… - Mastodon",
    "sm_trust_messenger": "How much do you trust news or information you see on… - Facebook Messenger",
    "sm_trust_post": "How much do you trust news or information you see on… - Post",
    "sm_trust_snapchat": "How much do you trust news or information you see on… - Snapchat",
    "sm_trust_4chan": "How much do you trust news or information you see on… - 4chan",
    "sm_trust_tumblr": "How much do you trust news or information you see on… - Tumblr",
    "sm_trust_threads": "How much do you trust news or information you see on… - Threads",
    "sm_trust_bluesky": "How much do you trust news or information you see on… - Bluesky",

    # POL_POST_COLUMNS
    "sm_post_pol_gab": "How often do you post about politics on the following platforms? - Gab",
    "sm_post_pol_facebook": "How often do you post about politics on the following platforms? - Facebook",
    "sm_post_pol_instagram": "How often do you post about politics on the following platforms? - Instagram",
    "sm_post_pol_linkedin": "How often do you post about politics on the following platforms? - LinkedIn",
    "sm_post_pol_pinterest": "How often do you post about politics on the following platforms? - Pinterest",
    "sm_post_pol_reddit": "How often do you post about politics on the following platforms? - Reddit",
    "sm_post_pol_tumblr": "How often do you post about politics on the following platforms? - Tumblr",
    "sm_post_pol_tiktok": "How often do you post about politics on the following platforms? - TikTok",
    "sm_post_pol_twitter": "How often do you post about politics on the following platforms? - X (Twitter)",
    "sm_post_pol_youtube": "How often do you post about politics on the following platforms? - YouTube",
    "sm_post_pol_whatsapp": "How often do you post about politics on the following platforms? - WhatsApp",
    "sm_post_pol_4chan": "How often do you post about politics on the following platforms? - 4chan",
    "sm_post_pol_truth": "How often do you post about politics on the following platforms? - Truth Social",
    "sm_post_pol_parler": "How often do you post about politics on the following platforms? - Parler",
    "sm_post_pol_mastodon": "How often do you post about politics on the following platforms? - Mastodon",
    "sm_post_pol_messenger": "How often do you post about politics on the following platforms? - Facebook Messenger",
    "sm_post_pol_post": "How often do you post about politics on the following platforms? - Post",
    "sm_post_pol_snapchat": "How often do you post about politics on the following platforms? - Snapchat",
    "sm_post_pol_threads": "How often do you post about politics on the following platforms? - Threads",
    "sm_post_pol_bluesky": "How often do you post about politics on the following platforms? - Bluesky",

    # POL_NEWS_COLUMNS
    "pol_news2_1": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Facebook (website or app)",
    "pol_news2_2": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Twitter (website or app)",
    "pol_news2_3": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Youtube (website or app)",
    "pol_news2_4": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Reddit (website or app)",
    "pol_news2_5": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Instagram (website or app)",
    "pol_news2_6": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Snapchat (website or app)",
    "pol_news2_7": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Wikipedia (website or app)",
    "pol_news2_8": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Facebook Messenger app",
    "pol_news2_9": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — WhatsApp app",
    "pol_news2_10": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — TikTok app",
    "pol_news2_11": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — None of the above",
    "pol_news2_12": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Truth Social App",

    # POL_NEWS1_COLUMNS
    "pol_news1_1": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Friends and family",
    "pol_news1_2": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Radio news",
    "pol_news1_3": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Podcasts",
    "pol_news1_4": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Local television",
    "pol_news1_5": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Network television (e.g. ABC, CBS, or NBC)",
    "pol_news1_6": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Cable television (e.g. CNN, Fox News, or MSNBC)",
    "pol_news1_7": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Late-night comedy shows (e.g. The Late Show with Stephen Colbert or The Daily Show)",
    "pol_news1_8": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Print newspapers (e.g. the New York Times or the Wall Street Journal print edition)",
    "pol_news1_9": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — A news website or app (e.g. the New York Times or Fox News websites or apps)",
    "pol_news1_13": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — A search engine website or app (e.g. Google, Bing)",
    "pol_news1_14": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — A social media website or app (e.g. Facebook, Twitter, Snapchat)",
    "pol_news1_15": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — A mobile instant message app (e.g. Facebook Messenger or WhatsApp)",
    "pol_news1_16": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — A community newspaper or website",
    "pol_news1_17": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Artificial Intelligence chatbots (e.g. ChatGPT, Gemini, Copilot)",

    # POL_TRUST_COLUMNS
    "pol_trust_science": "How much do you trust the following people and organizations to do what is right? - Scientists and researchers",
    "pol_trust_trump": "How much do you trust the following people and organizations to do what is right? - Donald Trump",
    "pol_trust_twitter": "How much do you trust the following organizations to do what is right? - Twitter",
    "pol_trust_social": "How much do you trust the following people and organizations to do what is right? - Social media companies",
    "pol_trust_google": "How much do you trust the following organizations to do what is right? - Google",
    "pol_trust_facebook": "How much do you trust the following organizations to do what is right? - Facebook",

    # COV_TRUST_COLUMNS
    "cov_trust_city": "How much do you trust the following people and organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - Your city government",
    "cov_trust_state": "How much do you trust the following people and organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - Your state government",
    "cov_trust_white_house": "How much do you trust the following people and organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - The White House",
    "cov_trust_congress": "How much do you trust the following people and organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - Congress",
    "cov_trust_trump": "How much do you trust the following people and organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - Donald Trump",
    "cov_trust_biden": "How much do you trust the following people and organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - Joe Biden",
    "cov_trust_cdc": "How much do you trust the following people and organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - The CDC (Centers for Disease Control and Prevention)",
    "cov_trust_fauci": "How much do you trust the following people and organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - Dr. Anthony Fauci of the National Institute of Health",
    "cov_trust_fda": "How much do you trust the following people and organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - The FDA (Food and Drug Administration)",
    "cov_trust_doctors": "How much do you trust the following people and organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - Hospitals and doctors",
    "cov_trust_pharma": "How much do you trust the following people and organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - Pharmaceutical companies",
    "cov_trust_science": "How much do you trust the following people and organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - Scientists and researchers",
    "cov_trust_police": "How much do you trust the following people and organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - The police",
    "cov_trust_banks": "How much do you trust the following people and organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - Banks",
    "cov_trust_media": "How much do you trust the following people and organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - The news media",
    "cov_trust_social": "How much do you trust the following people and organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - Social media companies",
    "cov_trust_cnn": "How much do you trust the following organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - CNN",
    "cov_trust_fox": "How much do you trust the following organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - Fox News",
    "cov_trust_nyt": "How much do you trust the following organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - The New York Times",
    "cov_trust_google": "How much do you trust the following organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - Google",
    "cov_trust_facebook": "How much do you trust the following organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - Facebook",
    "cov_trust_twitter": "How much do you trust the following organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - Twitter",

    # W38_POLITICAL_COLUMNS
    "state_dem": "How democratically is your state being governed today?",
    "gerry_eval": "Some states redraw congressional district boundaries in ways that make it easier for the party that controls the state government to win more seats in Congress. Do you think this is good or bad for democracy?",
    "gerry_amend": "Would you support or oppose a constitutional amendment that would prohibit states from redrawing congressional district boundaries to help one political party win more seats?",
    "gerry_state_aware": "As far as you know, is your state currently redrawing congressional district boundaries?",
    "support_cuba": "Would you support or oppose the US using military force to overthrow the current Cuban government?",

    # PHQ9_COLUMNS
    "phq9_1": "Little interest or pleasure in doing things",
    "phq9_2": "Feeling down, depressed, or hopeless",
    "phq9_3": "Trouble falling or staying asleep, or sleeping too much",
    "phq9_4": "Feeling tired or having little energy",
    "phq9_5": "Poor appetite or overeating",
    "phq9_6": "Feeling bad about yourself - or that you are a failure or have let yourself or your family down",
    "phq9_7": "Trouble concentrating on things, such as reading the newspaper or watching television",
    "phq9_8": "Moving or speaking so slowly that other people could have noticed -- or so fidgety or restless that you have been moving a lot more than usual",
    "phq9_9": "Thoughts that you would be better off dead, or thoughts of hurting yourself in some way",
    "phq9_10": "Feeling nervous, anxious or on edge",
    "phq9_11": "Not being able to stop or control worrying",
    "phq9_12": "Experiencing weakness in your right arm",

    # RACE_BOOLEAN_COLUMNS
    "race_asian": "What racial or ethnic group best describes you? (Please select all that apply) — Asian American",
    "race_black": "What racial or ethnic group best describes you? (Please select all that apply) — African American",
    "race_hisp": "What racial or ethnic group best describes you? (Please select all that apply) — Hispanic",
    "race_natam": "What racial or ethnic group best describes you? (Please select all that apply) — Native American",
    "race_white": "What racial or ethnic group best describes you? (Please select all that apply) — White",
    "race_other": "What racial or ethnic group best describes you? (Please select all that apply) — Other",

    # GEN_POST_COLUMNS
    "sm_post_gen_4chan": "How often do you post anything on the following platforms? - 4chan",
    "sm_post_gen_facebook": "How often do you post anything on the following platforms? - Facebook",
    "sm_post_gen_gab": "How often do you post anything on the following platforms? - Gab",
    "sm_post_gen_instagram": "How often do you post anything on the following platforms? - Instagram",
    "sm_post_gen_linkedin": "How often do you post anything on the following platforms? - LinkedIn",
    "sm_post_gen_mastodon": "How often do you post anything on the following platforms? - Mastodon",
    "sm_post_gen_messenger": "How often do you post anything on the following platforms? - Facebook Messenger",
    "sm_post_gen_parler": "How often do you post anything on the following platforms? - Parler",
    "sm_post_gen_pinterest": "How often do you post anything on the following platforms? - Pinterest",
    "sm_post_gen_post": "How often do you post anything on the following platforms? - Post",
    "sm_post_gen_reddit": "How often do you post anything on the following platforms? - Reddit",
    "sm_post_gen_snapchat": "How often do you post anything on the following platforms? - Snapchat",
    "sm_post_gen_tiktok": "How often do you post anything on the following platforms? - TikTok",
    "sm_post_gen_truth": "How often do you post anything on the following platforms? - Truth Social",
    "sm_post_gen_tumblr": "How often do you post anything on the following platforms? - Tumblr",
    "sm_post_gen_twitter": "How often do you post anything on the following platforms? - X (Twitter)",
    "sm_post_gen_whatsapp": "How often do you post anything on the following platforms? - WhatsApp",
    "sm_post_gen_youtube": "How often do you post anything on the following platforms? - YouTube",
    "sm_post_gen_bluesky": "How often do you post anything on the following platforms? - Bluesky",
    "sm_post_gen_threads": "How often do you post anything on the following platforms? - Threads",
    "sm_post_gen_bereal": "How often do you post anything on the following platforms? - BeReal",
    "sm_post_gen_lemon8": "How often do you post anything on the following platforms? - Lemon8",
    "sm_post_gen_rednote": "How often do you post anything on the following platforms? - Rednote",
    "sm_post_gen_twitch": "How often do you post anything on the following platforms? - Twitch",

    # COV_BEH_COLUMNS
    "cov_beh_1": "In the last week, how closely did you personally follow the health behaviors listed below? — Avoiding contact with other people",
    "cov_beh_2": "In the last week, how closely did you personally follow the health behaviors listed below? — Avoiding public or crowded places",
    "cov_beh_3": "In the last week, how closely did you personally follow the health behaviors listed below? — Frequently washing hands",
    "cov_beh_4": "In the last week, how closely did you personally follow the health behaviors listed below? — Disinfecting often-touched surfaces",
    "cov_beh_5": "In the last week, how closely did you personally follow the health behaviors listed below? — Wearing a face mask when outside of your home",

    # ELECTION_COLUMNS
    "democ_1": "On a scale from 0 to 100, where 0 is least democratic and 100 is most democratic, how would you rate the political system of the United States as of today? - U.S. Political System",
    "cand24": "If the 2024 U.S. presidential election were held today, which candidate would you vote for? - Selected Choice",
    "vote24": "Do you plan to vote in the 2024 U.S. presidential election?",
    "news_elect_1": "How important is the information you get from news outlets for your decision how to vote in local, state, and congressional elections? — Local elections",
    "news_elect_2": "How important is the information you get from news outlets for your decision how to vote in local, state, and congressional elections? — State elections",
    "news_elect_3": "How important is the information you get from news outlets for your decision how to vote in local, state, and congressional elections? — Congressional elections",
    "source_elect": "When making a decision about voting, including candidates for office and ballot initiatives, what is your most important source of information? - Selected Choice",
    "media_elect": "Which source of news stories is most important to you when it comes to making a decision about voting? - Selected Choice",
    "news_sat": "How satisfied are you with the quality of news you get about local government and local politics?",

    # OZEMPIC_COLUMNS
    "ozempic": "Have you ever used GLP-1 medications like Ozempic, Wegovy, Mounjaro, or Zepbound for weight loss or diabetes management?",
    "ozempic_why": "Have you used a GLP-1 medication for diabetes management, weight loss, or both?",
    "ozempic_time_1": "For how long did you take a GLP-1 medication? (years)",
    "ozempic_time_2": "For how long did you take a GLP-1 medication? (months)",
}
