"""
Survey question wording for each CHIP50 variable.

Sourced from the COVID States Project survey text archive
(https://github.com/kateto/COVID19/tree/master/SURVEYS), which publishes the
exact Qualtrics question wording and response options for every wave. For each
variable, the wording is taken from the most recent wave in which it was
fielded. Where a variable is one item in a matrix/multi-select question (e.g.
platform-specific trust or usage items, or pol_news1_N / pol_news2_N source
checkboxes), the stem question is combined with the item-specific label.
"""

QUESTION_WORDING: dict[str, str] = {
    # DEMOGRAPHIC_COLUMNS
    "age_cat_8": "Age range (8 categories)",
    "education_cat": "Education level (5 categories)",
    "income_cat_10": "What was the total combined income of your household for the past year?",
    "race_cat_5": "Race as provided by vendor (select one, 5 categories)",
    "gender": "Gender as provided by vendor (M/F only)",
    "party3": "Political party",
    "party7": "Political affiliation",
    "urban_type": "Urban type (NCHS)",
    "state": "State name Text entry:______________",
    "state_code": "Two-letter state code Text entry:______________",

    # PLATFORM_COLUMNS
    "use_facebook": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — Facebook",
    "use_instagram": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — Instagram",
    "use_youtube": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — YouTube",
    "use_twitter": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — X (Twitter)",
    "use_tiktok": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — TikTok",
    "use_snapchat": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — Snapchat",
    "use_linkedin": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — LinkedIn",
    "use_reddit": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — Reddit",
    "use_whatsapp": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — WhatsApp",
    "use_messenger": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — Facebook Messenger",
    "use_pinterest": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — Pinterest",
    "use_tumblr": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — Tumblr",
    "use_gab": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — Gab",
    "use_parler": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — Parler",
    "use_4chan": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — 4chan",
    "use_truth": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — Truth Social",
    "use_mastodon": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — Mastodon",
    "use_post": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — Post",
    "use_threads": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — Threads",
    "use_bluesky": "Do you ever use any of the following social media sites or apps? (Please select all that apply) — Bluesky",

    # ATTITUDINAL_COLUMNS
    "ideology": "In general, do you think of yourself as...",
    "economy": "How would you rate economic conditions in this country today?",
    "voted20": "Which candidate did you vote for in the 2020 U.S. presidential election? - Selected Choice",
    "voted24": "Which candidate did you vote for in the 2024 U.S. presidential election? - Selected Choice",
    "trump_win": "How much do you agree or disagree with the following statement: “If votes were fairly counted, Donald Trump would have won the 2020 election”",
    "conspiracy_1": "Even though we live in a democracy, a few people will always run things anyway.",
    "conspiracy_2": "The people who really 'run' the country are not known to the voters",
    "conspiracy_3": "Big events like wars, recessions, and the outcomes of elections are controlled by small groups of people who are working in secret against the rest of us.",
    "conspiracy_4": "Much of our lives are being controlled by plots hatched in secret places",
    "pol_info": "How closely do you follow news and information about politics and current affairs?",
    "pol_disc": "How often do you talk to people about politics and current affairs, either in person, over the phone, or electronically?",
    "trump_gen": "Do you approve or disapprove of the way Donald Trump is handling his job as president?",
    "age": "Respondent age (in years)",

    # FREQ_COLUMNS
    "freq_facebook": "How often do you use the following social media platforms? - Facebook",
    "freq_instagram": "How often do you use the following social media platforms? - Instagram",
    "freq_youtube": "How often do you use the following social media platforms? - YouTube",
    "freq_twitter": "How often do you use the following social media platforms? - X (Twitter)",
    "freq_tiktok": "How often do you use the following social media platforms? - TikTok",
    "freq_snapchat": "How often do you use the following social media platforms? - Snapchat",
    "freq_linkedin": "How often do you use the following social media platforms? - LinkedIn",
    "freq_reddit": "How often do you use the following social media platforms? - Reddit",
    "freq_whatsapp": "How often do you use the following social media platforms? - WhatsApp",
    "freq_messenger": "How often do you use the following social media platforms? - Facebook Messenger",
    "freq_pinterest": "How often do you use the following social media platforms? - Pinterest",
    "freq_tumblr": "How often do you use the following social media platforms? - Tumblr",
    "freq_gab": "How often do you use the following social media platforms? - Gab",
    "freq_parler": "How often do you use the following social media platforms? - Parler",
    "freq_4chan": "How often do you use the following social media platforms? - 4chan",
    "freq_truth": "How often do you use the following social media platforms? - Truth Social",
    "freq_mastodon": "How often do you use the following social media platforms? - Mastodon",
    "freq_post": "How often do you use the following social media platforms? - Post",
    "freq_threads": "How often do you use the following social media platforms? - Threads",
    "freq_bluesky": "How often do you use the following social media platforms? - Bluesky",

    # TRUST_COLUMNS
    "sm_trust_youtube": "How much do you trust news or information you see on… - YouTube",
    "sm_trust_facebook": "How much do you trust news or information you see on… - Facebook",
    "sm_trust_twitter": "How much do you trust news or information you see on… - X (Twitter)",
    "sm_trust_instagram": "How much do you trust news or information you see on… - Instagram",
    "sm_trust_reddit": "How much do you trust news or information you see on… - Reddit",
    "sm_trust_tiktok": "How much do you trust news or information you see on… - TikTok",
    "sm_trust_whatsapp": "How much do you trust news or information you see on… - WhatsApp",
    "sm_trust_linkedin": "How much do you trust news or information you see on… - LinkedIn",
    "sm_trust_truth": "How much do you trust news or information you see on… - Truth Social",
    "sm_trust_parler": "How much do you trust news or information you see on… - Parler",
    "sm_trust_mastodon": "How much do you trust news or information you see on… - Mastodon",
    "sm_trust_messenger": "How much do you trust news or information you see on… - Facebook Messenger",
    "sm_trust_post": "How much do you trust news or information you see on… - Post",
    "sm_trust_snapchat": "How much do you trust news or information you see on… - Snapchat",
    "sm_trust_4chan": "How much do you trust news or information you see on… - 4chan",
    "sm_trust_tumblr": "How much do you trust news or information you see on… - Tumblr",
    "sm_trust_threads": "How much do you trust news or information you see on… - Threads",
    "sm_trust_bluesky": "How much do you trust news or information you see on… - Bluesky",

    # POL_POST_COLUMNS
    "sm_post_pol_gab": "How often do you post about politics on the following platforms? - Gab",
    "sm_post_pol_facebook": "How often do you post about politics on the following platforms? - Facebook",
    "sm_post_pol_instagram": "How often do you post about politics on the following platforms? - Instagram",
    "sm_post_pol_linkedin": "How often do you post about politics on the following platforms? - LinkedIn",
    "sm_post_pol_pinterest": "How often do you post about politics on the following platforms? - Pinterest",
    "sm_post_pol_reddit": "How often do you post about politics on the following platforms? - Reddit",
    "sm_post_pol_tumblr": "How often do you post about politics on the following platforms? - Tumblr",
    "sm_post_pol_tiktok": "How often do you post about politics on the following platforms? - TikTok",
    "sm_post_pol_twitter": "How often do you post about politics on the following platforms? - X (Twitter)",
    "sm_post_pol_youtube": "How often do you post about politics on the following platforms? - YouTube",
    "sm_post_pol_whatsapp": "How often do you post about politics on the following platforms? - WhatsApp",
    "sm_post_pol_4chan": "How often do you post about politics on the following platforms? - 4chan",
    "sm_post_pol_truth": "How often do you post about politics on the following platforms? - Truth Social",
    "sm_post_pol_parler": "How often do you post about politics on the following platforms? - Parler",
    "sm_post_pol_mastodon": "How often do you post about politics on the following platforms? - Mastodon",
    "sm_post_pol_messenger": "How often do you post about politics on the following platforms? - Facebook Messenger",
    "sm_post_pol_post": "How often do you post about politics on the following platforms? - Post",
    "sm_post_pol_snapchat": "How often do you post about politics on the following platforms? - Snapchat",
    "sm_post_pol_threads": "How often do you post about politics on the following platforms? - Threads",
    "sm_post_pol_bluesky": "How often do you post about politics on the following platforms? - Bluesky",

    # POL_NEWS_COLUMNS
    "pol_news2_1": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Facebook (website or app)",
    "pol_news2_2": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Twitter (website or app)",
    "pol_news2_3": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Youtube (website or app)",
    "pol_news2_4": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Reddit (website or app)",
    "pol_news2_5": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Instagram (website or app)",
    "pol_news2_6": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Snapchat (website or app)",
    "pol_news2_7": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Wikipedia (website or app)",
    "pol_news2_8": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Facebook Messenger app",
    "pol_news2_9": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — WhatsApp app",
    "pol_news2_10": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — TikTok app",
    "pol_news2_11": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — None of the above",
    "pol_news2_12": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Truth Social App",

    # POL_NEWS1_COLUMNS
    "pol_news1_1": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Friends and family",
    "pol_news1_2": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Radio news",
    "pol_news1_3": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Podcasts",
    "pol_news1_4": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Local television",
    "pol_news1_5": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Network television (e.g. ABC, CBS, or NBC)",
    "pol_news1_6": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Cable television (e.g. CNN, Fox News, or MSNBC)",
    "pol_news1_7": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Late-night comedy shows (e.g. The Late Show with Stephen Colbert or The Daily Show)",
    "pol_news1_8": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Print newspapers (e.g. the New York Times or the Wall Street Journal print edition)",
    "pol_news1_9": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — A news website or app (e.g. the New York Times or Fox News websites or apps)",
    "pol_news1_13": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — A search engine website or app (e.g. Google, Bing)",
    "pol_news1_14": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — A social media website or app (e.g. Facebook, Twitter, Snapchat)",
    "pol_news1_15": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — A mobile instant message app (e.g. Facebook Messenger or WhatsApp)",
    "pol_news1_16": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — A community newspaper or website",
    "pol_news1_17": "In the last 24 hours, did you get any news or information about politics and current affairs from the following sources? — Artificial Intelligence chatbots (e.g. ChatGPT, Gemini, Copilot)",

    # POL_TRUST_COLUMNS
    "pol_trust_science": "How much do you trust the following people and organizations to do what is right? - Scientists and researchers",
    "pol_trust_trump": "How much do you trust the following people and organizations to do what is right? - Donald Trump",
    "pol_trust_twitter": "How much do you trust the following organizations to do what is right? - Twitter",
    "pol_trust_social": "How much do you trust the following people and organizations to do what is right? - Social media companies",
    "pol_trust_google": "How much do you trust the following organizations to do what is right? - Google",
    "pol_trust_facebook": "How much do you trust the following organizations to do what is right? - Facebook",

    # COV_TRUST_COLUMNS
    "cov_trust_city": "How much do you trust the following people and organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - Your city government",
    "cov_trust_state": "How much do you trust the following people and organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - Your state government",
    "cov_trust_white_house": "How much do you trust the following people and organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - The White House",
    "cov_trust_congress": "How much do you trust the following people and organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - Congress",
    "cov_trust_trump": "How much do you trust the following people and organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - Donald Trump",
    "cov_trust_biden": "How much do you trust the following people and organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - Joe Biden",
    "cov_trust_cdc": "How much do you trust the following people and organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - The CDC (Centers for Disease Control and Prevention)",
    "cov_trust_fauci": "How much do you trust the following people and organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - Dr. Anthony Fauci of the National Institute of Health",
    "cov_trust_fda": "How much do you trust the following people and organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - The FDA (Food and Drug Administration)",
    "cov_trust_doctors": "How much do you trust the following people and organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - Hospitals and doctors",
    "cov_trust_pharma": "How much do you trust the following people and organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - Pharmaceutical companies",
    "cov_trust_science": "How much do you trust the following people and organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - Scientists and researchers",
    "cov_trust_police": "How much do you trust the following people and organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - The police",
    "cov_trust_banks": "How much do you trust the following people and organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - Banks",
    "cov_trust_media": "How much do you trust the following people and organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - The news media",
    "cov_trust_social": "How much do you trust the following people and organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - Social media companies",
    "cov_trust_cnn": "How much do you trust the following organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - CNN",
    "cov_trust_fox": "How much do you trust the following organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - Fox News",
    "cov_trust_nyt": "How much do you trust the following organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - The New York Times",
    "cov_trust_google": "How much do you trust the following organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - Google",
    "cov_trust_facebook": "How much do you trust the following organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - Facebook",
    "cov_trust_twitter": "How much do you trust the following organizations to do the right thing to best handle the current coronavirus (COVID-19) outbreak? - Twitter",

    # W38_POLITICAL_COLUMNS
    "state_dem": "How democratically is your state being governed today?",
    "gerry_eval": "Some states redraw congressional district boundaries in ways that make it easier for the party that controls the state government to win more seats in Congress. Do you think this is good or bad for democracy?",
    "gerry_amend": "Would you support or oppose a constitutional amendment that would prohibit states from redrawing congressional district boundaries to help one political party win more seats?",
    "gerry_state_aware": "As far as you know, is your state currently redrawing congressional district boundaries?",
    "support_cuba": "Would you support or oppose the US using military force to overthrow the current Cuban government?",

    # PHQ9_COLUMNS
    "phq9_1": "Little interest or pleasure in doing things",
    "phq9_2": "Feeling down, depressed, or hopeless",
    "phq9_3": "Trouble falling or staying asleep, or sleeping too much",
    "phq9_4": "Feeling tired or having little energy",
    "phq9_5": "Poor appetite or overeating",
    "phq9_6": "Feeling bad about yourself - or that you are a failure or have let yourself or your family down",
    "phq9_7": "Trouble concentrating on things, such as reading the newspaper or watching television",
    "phq9_8": "Moving or speaking so slowly that other people could have noticed -- or so fidgety or restless that you have been moving a lot more than usual",
    "phq9_9": "Thoughts that you would be better off dead, or thoughts of hurting yourself in some way",
    "phq9_10": "Feeling nervous, anxious or on edge",
    "phq9_11": "Not being able to stop or control worrying",
    "phq9_12": "Experiencing weakness in your right arm",

    # RACE_BOOLEAN_COLUMNS
    "race_asian": "What racial or ethnic group best describes you? (Please select all that apply) — Asian American",
    "race_black": "What racial or ethnic group best describes you? (Please select all that apply) — African American",
    "race_hisp": "What racial or ethnic group best describes you? (Please select all that apply) — Hispanic",
    "race_natam": "What racial or ethnic group best describes you? (Please select all that apply) — Native American",
    "race_white": "What racial or ethnic group best describes you? (Please select all that apply) — White",
    "race_other": "What racial or ethnic group best describes you? (Please select all that apply) — Other",

    # GEN_POST_COLUMNS
    "sm_post_gen_4chan": "How often do you post anything on the following platforms? - 4chan",
    "sm_post_gen_facebook": "How often do you post anything on the following platforms? - Facebook",
    "sm_post_gen_gab": "How often do you post anything on the following platforms? - Gab",
    "sm_post_gen_instagram": "How often do you post anything on the following platforms? - Instagram",
    "sm_post_gen_linkedin": "How often do you post anything on the following platforms? - LinkedIn",
    "sm_post_gen_mastodon": "How often do you post anything on the following platforms? - Mastodon",
    "sm_post_gen_messenger": "How often do you post anything on the following platforms? - Facebook Messenger",
    "sm_post_gen_parler": "How often do you post anything on the following platforms? - Parler",
    "sm_post_gen_pinterest": "How often do you post anything on the following platforms? - Pinterest",
    "sm_post_gen_post": "How often do you post anything on the following platforms? - Post",
    "sm_post_gen_reddit": "How often do you post anything on the following platforms? - Reddit",
    "sm_post_gen_snapchat": "How often do you post anything on the following platforms? - Snapchat",
    "sm_post_gen_tiktok": "How often do you post anything on the following platforms? - TikTok",
    "sm_post_gen_truth": "How often do you post anything on the following platforms? - Truth Social",
    "sm_post_gen_tumblr": "How often do you post anything on the following platforms? - Tumblr",
    "sm_post_gen_twitter": "How often do you post anything on the following platforms? - X (Twitter)",
    "sm_post_gen_whatsapp": "How often do you post anything on the following platforms? - WhatsApp",
    "sm_post_gen_youtube": "How often do you post anything on the following platforms? - YouTube",
    "sm_post_gen_bluesky": "How often do you post anything on the following platforms? - Bluesky",
    "sm_post_gen_threads": "How often do you post anything on the following platforms? - Threads",
    "sm_post_gen_bereal": "How often do you post anything on the following platforms? - BeReal",
    "sm_post_gen_lemon8": "How often do you post anything on the following platforms? - Lemon8",
    "sm_post_gen_rednote": "How often do you post anything on the following platforms? - Rednote",
    "sm_post_gen_twitch": "How often do you post anything on the following platforms? - Twitch",

    # VACCINATION_COLUMNS
    "vaccine_get": "How likely are you to get a COVID-19 vaccine when one is available to you? (1=Definitely will, 5=Definitely will not)",
    "kff_vacc1": "Have you received at least one dose of a COVID-19 vaccine? (1=Yes, 2=No) — KFF COVID-19 Vaccine Monitor",
    "vac_boost": "How many COVID-19 booster doses have you received? (0=None, 1–5=number of boosters; -99=skipped/refused)",
    "vac_ref": "What is the main reason you have not gotten a COVID-19 vaccine? (ordinal 1–4; -99=skipped/refused)",
    "vac_total": "Total number of COVID-19 vaccine doses received, including boosters (0=none; 99=don't know; -99=skipped/refused)",

    # COV_BEH_COLUMNS
    "cov_beh_1": "In the last week, how closely did you personally follow the health behaviors listed below? — Avoiding contact with other people",
    "cov_beh_2": "In the last week, how closely did you personally follow the health behaviors listed below? — Avoiding public or crowded places",
    "cov_beh_3": "In the last week, how closely did you personally follow the health behaviors listed below? — Frequently washing hands",
    "cov_beh_4": "In the last week, how closely did you personally follow the health behaviors listed below? — Disinfecting often-touched surfaces",
    "cov_beh_5": "In the last week, how closely did you personally follow the health behaviors listed below? — Wearing a face mask when outside of your home",

    # ELECTION_COLUMNS
    "democ_1": "On a scale from 0 to 100, where 0 is least democratic and 100 is most democratic, how would you rate the political system of the United States as of today? - U.S. Political System",
    "cand24": "If the 2024 U.S. presidential election were held today, which candidate would you vote for? - Selected Choice",
    "vote24": "Do you plan to vote in the 2024 U.S. presidential election?",
    "news_elect_1": "How important is the information you get from news outlets for your decision how to vote in local, state, and congressional elections? — Local elections",
    "news_elect_2": "How important is the information you get from news outlets for your decision how to vote in local, state, and congressional elections? — State elections",
    "news_elect_3": "How important is the information you get from news outlets for your decision how to vote in local, state, and congressional elections? — Congressional elections",
    "source_elect": "When making a decision about voting, including candidates for office and ballot initiatives, what is your most important source of information? - Selected Choice",
    "media_elect": "Which source of news stories is most important to you when it comes to making a decision about voting? - Selected Choice",
    "news_sat": "How satisfied are you with the quality of news you get about local government and local politics?",

    # OZEMPIC_COLUMNS
    "ozempic": "Have you ever used GLP-1 medications like Ozempic, Wegovy, Mounjaro, or Zepbound for weight loss or diabetes management?",
    "ozempic_why": "Have you used a GLP-1 medication for diabetes management, weight loss, or both?",
    "ozempic_time_1": "For how long did you take a GLP-1 medication? (years)",
    "ozempic_time_2": "For how long did you take a GLP-1 medication? (months)",

    # FAKE_NEWS_COLUMNS
    # Misinformation belief / news discernment items (ordinal; -99 = skipped/refused; NULL = not asked)
    # Exact wording varies by wave — see CHIP50 variable dictionary for per-item text.
    "fn_1":  "Fake news / misinformation item 1 (ordinal)",
    "fn_2":  "Fake news / misinformation item 2 (ordinal)",
    "fn_3":  "Fake news / misinformation item 3 (ordinal)",
    "fn_6":  "Fake news / misinformation item 6 (ordinal)",
    "fn_8":  "Fake news / misinformation item 8 (ordinal)",
    "fn_9":  "Fake news / misinformation item 9 (ordinal)",
    "fn_10": "Fake news / misinformation item 10 (ordinal)",
    "fn_11": "Fake news / misinformation item 11 (ordinal)",
    "fn_12": "Fake news / misinformation item 12 (ordinal)",
    "fn_13": "Fake news / misinformation item 13 (ordinal)",
    "fn_14": "Fake news / misinformation item 14 (ordinal)",
    "fn_15": "Fake news / misinformation item 15 (ordinal)",
    "fn_16": "Fake news / misinformation item 16 (ordinal)",
    "fn_20": "Fake news / misinformation item 20 (ordinal)",
    "fn_21": "Fake news / misinformation item 21 (ordinal)",
    "fn_22": "Fake news / misinformation item 22 (ordinal)",
    "fn_23": "Fake news / misinformation item 23 (ordinal)",
    "fn_30": "Fake news / misinformation item 30 (ordinal)",
    "fn_31": "Fake news / misinformation item 31 (ordinal)",
    "fn_33": "Fake news / misinformation item 33 (ordinal)",
    "fn_34": "Fake news / misinformation item 34 (ordinal)",
    "fn_35": "Fake news / misinformation item 35 (ordinal)",
    "fn_36": "Fake news / misinformation item 36 (ordinal)",
    "fn_38": "Fake news / misinformation item 38 (ordinal)",
    "fn_40": "Fake news / misinformation item 40 (ordinal)",
    "fn_43": "Fake news / misinformation item 43 (ordinal)",
    "fn_44": "Fake news / misinformation item 44 (ordinal)",
    "fn_45": "Fake news / misinformation item 45 (ordinal)",
    "fn_47": "Fake news / misinformation item 47 (ordinal)",

    # CAP_FN_COLUMNS
    # Fact-checking capacity / behavior items (binary 0/1; NULL = not asked this wave)
    "cap_fn_1": "Fact-checking behavior / capacity item 1 (binary 0/1)",
    "cap_fn_2": "Fact-checking behavior / capacity item 2 (binary 0/1)",
    "cap_fn_3": "Fact-checking behavior / capacity item 3 (binary 0/1)",
    "cap_fn_4": "Fact-checking behavior / capacity item 4 (binary 0/1)",
    "cap_fn_5": "Fact-checking behavior / capacity item 5 (binary 0/1)",
    "cap_fn_6": "Fact-checking behavior / capacity item 6 (binary 0/1)",

    # FR_POL_COLUMNS
    "fr_pol_4": "Political discussion frequency follow-up item 4 (ordinal; -99 = skipped/refused)",
    "fr_pol_6": "Political discussion frequency follow-up item 6 (ordinal; -99 = skipped/refused)",

    # PROT_COLUMNS
    "prot_cause_elect": "Protest cause — election-related (binary 0/1; 1 = participated in election-related protest)",
    "prot_pan_cause_2": "Pandemic protest cause item 2 (binary 0/1)",

    # ELECTION_INTEGRITY_COLUMNS
    "el_conf":    "How confident are you that votes in U.S. elections are counted accurately? (ordinal; -99 = skipped/refused)",
    "el_conf_22": "How confident are you that votes in the 2022 U.S. midterm elections were counted accurately? (ordinal; -99 = skipped/refused)",
    "el_conf_24": "How confident are you that votes in the 2024 U.S. presidential election were counted accurately? (ordinal; -99 = skipped/refused)",
    "el_conf_26": "How confident are you that votes in the 2026 U.S. midterm elections will be counted accurately? (ordinal; -99 = skipped/refused)",
    "el_count":   "How confident are you that votes in elections are counted accurately — summary/overall item (ordinal; -99 = skipped/refused)",
    "el_fair_1":  "Election fairness perception item 1 (ordinal; -99 = skipped/refused)",
    "el_fair_2":  "Election fairness perception item 2 (ordinal; -99 = skipped/refused)",
    "el_fair_3":  "Election fairness perception item 3 (ordinal; -99 = skipped/refused)",
    "el_fair_4":  "Election fairness perception item 4 (ordinal; -99 = skipped/refused)",
    "el_chal_1":  "Support for challenging election results — item 1 (ordinal; -99 = skipped/refused)",
    "el_chal_2":  "Support for challenging election results — item 2 (ordinal; -99 = skipped/refused)",
    "el_chal_3":  "Support for challenging election results — item 3 (ordinal; -99 = skipped/refused)",
    "el_chal_4":  "Support for challenging election results — item 4 (ordinal; -99 = skipped/refused)",
    "el_trust_biden":  "How much do you trust the following to ensure fair elections? — Joe Biden (ordinal; -99 = skipped/refused)",
    "el_trust_court":  "How much do you trust the following to ensure fair elections? — The courts (ordinal; -99 = skipped/refused)",
    "el_trust_police": "How much do you trust the following to ensure fair elections? — The police (ordinal; -99 = skipped/refused)",
    "ballot_access":        "How easy or difficult is it to access your ballot / vote in your area? (ordinal; -99 = skipped/refused)",
    "vote_counted":         "How confident are you that your own vote was/will be counted correctly? (ordinal; -99 = skipped/refused)",
    "vote_counted_state":   "How confident are you that votes in your state were/will be counted correctly? (ordinal; -99 = skipped/refused)",
    "voted_counted_nation": "How confident are you that votes nationally were/will be counted correctly? (ordinal; -99 = skipped/refused)",

    # ELECTION_CONCERN_COLUMNS
    "el_conc_1": "Election concern item 1 — specific concern about election integrity (binary 0/1; select all that apply)",
    "el_conc_2": "Election concern item 2 — specific concern about election integrity (binary 0/1; select all that apply)",
    "el_conc_3": "Election concern item 3 — specific concern about election integrity (binary 0/1; select all that apply)",
    "el_conc_4": "Election concern item 4 — specific concern about election integrity (binary 0/1; select all that apply)",
    "el_conc_5": "Election concern item 5 — specific concern about election integrity (binary 0/1; select all that apply)",
    "el_conc_6": "Election concern item 6 — specific concern about election integrity (binary 0/1; select all that apply)",

    # POL_TRUST_COLUMNS (extended)
    "pol_trust_ai":       "How much do you trust the following to do what is right? — AI companies / artificial intelligence (ordinal 1–4; -99 = skipped/refused)",
    "pol_trust_election": "How much do you trust the following to do what is right? — Election administration / officials (ordinal 1–4; -99 = skipped/refused)",

    # AI_ATTITUDE_COLUMNS
    "ai_regulation":  "Do you think AI should be regulated by the government? (ordinal; -99 = skipped/refused)",
    "ai_work_impact": "How do you think AI will affect your job or the jobs of people like you? (ordinal; -99 = skipped/refused)",
    "llm_psych":      "Do you think AI / large language models could negatively affect people's mental health or psychological wellbeing? (ordinal; -99 = skipped/refused)",
    "llm_help":       "Do you think AI / large language models could help people with everyday tasks? (ordinal; -99 = skipped/refused)",
    "survey_ai_use":   "Did you use any AI tools to help you complete this survey? (ordinal; -99 = skipped/refused)",
    "survey_ai_agent": "Did you use an AI agent to help complete this survey? (ordinal; -99 = skipped/refused)",
    "survey_ai_tools": "Which AI tools did you use to help complete this survey? (ordinal; -99 = skipped/refused)",
    "survey_ai_mode":  "How did you use AI when completing this survey? (ordinal; -99 = skipped/refused)",

    # AI_FREQ_COLUMNS
    # ai_freq_x1–x11: Frequency of use for each AI tool the respondent mentioned, in the order mentioned.
    # Ordinal scale; -99 = skipped/refused; NULL = respondent did not mention an Nth tool.
    "ai_freq_x1":  "Frequency of use — AI tool mentioned 1st by respondent (ordinal 1–6; 1=rarely, 6=several times a day)",
    "ai_freq_x2":  "Frequency of use — AI tool mentioned 2nd by respondent (ordinal 1–6)",
    "ai_freq_x3":  "Frequency of use — AI tool mentioned 3rd by respondent (ordinal 1–6)",
    "ai_freq_x4":  "Frequency of use — AI tool mentioned 4th by respondent (ordinal 1–6)",
    "ai_freq_x5":  "Frequency of use — AI tool mentioned 5th by respondent (ordinal 1–6)",
    "ai_freq_x6":  "Frequency of use — AI tool mentioned 6th by respondent (ordinal 1–6)",
    "ai_freq_x7":  "Frequency of use — AI tool mentioned 7th by respondent (ordinal 1–6)",
    "ai_freq_x8":  "Frequency of use — AI tool mentioned 8th by respondent (ordinal 1–6)",
    "ai_freq_x9":  "Frequency of use — AI tool mentioned 9th by respondent (ordinal 1–6)",
    "ai_freq_x10": "Frequency of use — AI tool mentioned 10th by respondent (ordinal 1–6)",
    "ai_freq_x11": "Frequency of use — AI tool mentioned 11th by respondent (ordinal 1–6)",
    "ai_freq_ai":    "Frequency of using any AI tool (ordinal 1–7; 1=rarely, 7=several times a day; waves 32/35)",
    "ai_freq_genai": "Frequency of using any generative AI tool (ordinal 1–7; 1=rarely, 7=several times a day; waves 32/35)",

    # AI_WHY_POS_COLUMNS
    # Why the respondent uses the AI tool in position N (binary 0/1; 3 reasons asked per tool).
    # Reasons: 1=fun/entertainment, 2=work/school/productivity, 3=news/information — confirm against questionnaire.
    "ai_why_x1_1":  "Reason 1 for using AI tool mentioned 1st (binary 0/1)",
    "ai_why_x1_2":  "Reason 2 for using AI tool mentioned 1st (binary 0/1)",
    "ai_why_x1_3":  "Reason 3 for using AI tool mentioned 1st (binary 0/1)",
    "ai_why_x2_1":  "Reason 1 for using AI tool mentioned 2nd (binary 0/1)",
    "ai_why_x2_2":  "Reason 2 for using AI tool mentioned 2nd (binary 0/1)",
    "ai_why_x2_3":  "Reason 3 for using AI tool mentioned 2nd (binary 0/1)",
    "ai_why_x3_1":  "Reason 1 for using AI tool mentioned 3rd (binary 0/1)",
    "ai_why_x3_2":  "Reason 2 for using AI tool mentioned 3rd (binary 0/1)",
    "ai_why_x3_3":  "Reason 3 for using AI tool mentioned 3rd (binary 0/1)",
    "ai_why_x4_1":  "Reason 1 for using AI tool mentioned 4th (binary 0/1)",
    "ai_why_x4_2":  "Reason 2 for using AI tool mentioned 4th (binary 0/1)",
    "ai_why_x4_3":  "Reason 3 for using AI tool mentioned 4th (binary 0/1)",
    "ai_why_x5_1":  "Reason 1 for using AI tool mentioned 5th (binary 0/1)",
    "ai_why_x5_2":  "Reason 2 for using AI tool mentioned 5th (binary 0/1)",
    "ai_why_x5_3":  "Reason 3 for using AI tool mentioned 5th (binary 0/1)",
    "ai_why_x6_1":  "Reason 1 for using AI tool mentioned 6th (binary 0/1)",
    "ai_why_x6_2":  "Reason 2 for using AI tool mentioned 6th (binary 0/1)",
    "ai_why_x6_3":  "Reason 3 for using AI tool mentioned 6th (binary 0/1)",
    "ai_why_x7_1":  "Reason 1 for using AI tool mentioned 7th (binary 0/1)",
    "ai_why_x7_2":  "Reason 2 for using AI tool mentioned 7th (binary 0/1)",
    "ai_why_x7_3":  "Reason 3 for using AI tool mentioned 7th (binary 0/1)",
    "ai_why_x8_1":  "Reason 1 for using AI tool mentioned 8th (binary 0/1)",
    "ai_why_x8_2":  "Reason 2 for using AI tool mentioned 8th (binary 0/1)",
    "ai_why_x8_3":  "Reason 3 for using AI tool mentioned 8th (binary 0/1)",
    "ai_why_x9_1":  "Reason 1 for using AI tool mentioned 9th (binary 0/1)",
    "ai_why_x9_2":  "Reason 2 for using AI tool mentioned 9th (binary 0/1)",
    "ai_why_x9_3":  "Reason 3 for using AI tool mentioned 9th (binary 0/1)",
    "ai_why_x10_1": "Reason 1 for using AI tool mentioned 10th (binary 0/1)",
    "ai_why_x10_2": "Reason 2 for using AI tool mentioned 10th (binary 0/1)",
    "ai_why_x10_3": "Reason 3 for using AI tool mentioned 10th (binary 0/1)",
    "ai_why_x11_1": "Reason 1 for using AI tool mentioned 11th (binary 0/1)",
    "ai_why_x11_2": "Reason 2 for using AI tool mentioned 11th (binary 0/1)",
    "ai_why_x11_3": "Reason 3 for using AI tool mentioned 11th (binary 0/1)",

    # AI_WHY_TOOL_COLUMNS
    # Why the respondent uses each named AI tool (binary 0/1; 3 reasons; NULL if tool not used)
    "ai_why_ai_1": "Reason 1 for using AI generally (binary 0/1)", "ai_why_ai_2": "Reason 2 for using AI generally (binary 0/1)", "ai_why_ai_3": "Reason 3 for using AI generally (binary 0/1)",
    "ai_why_anyword_1": "Reason 1 for using Anyword (binary 0/1)", "ai_why_anyword_2": "Reason 2 for using Anyword (binary 0/1)", "ai_why_anyword_3": "Reason 3 for using Anyword (binary 0/1)",
    "ai_why_bard_1": "Reason 1 for using Bard/Gemini (binary 0/1)", "ai_why_bard_2": "Reason 2 for using Bard/Gemini (binary 0/1)", "ai_why_bard_3": "Reason 3 for using Bard/Gemini (binary 0/1)",
    "ai_why_chatgpt_1": "Reason 1 for using ChatGPT (binary 0/1)", "ai_why_chatgpt_2": "Reason 2 for using ChatGPT (binary 0/1)", "ai_why_chatgpt_3": "Reason 3 for using ChatGPT (binary 0/1)",
    "ai_why_claude_1": "Reason 1 for using Claude (binary 0/1)", "ai_why_claude_2": "Reason 2 for using Claude (binary 0/1)", "ai_why_claude_3": "Reason 3 for using Claude (binary 0/1)",
    "ai_why_cohere_1": "Reason 1 for using Cohere (binary 0/1)", "ai_why_cohere_2": "Reason 2 for using Cohere (binary 0/1)", "ai_why_cohere_3": "Reason 3 for using Cohere (binary 0/1)",
    "ai_why_copilot_1": "Reason 1 for using Microsoft Copilot (binary 0/1)", "ai_why_copilot_2": "Reason 2 for using Microsoft Copilot (binary 0/1)", "ai_why_copilot_3": "Reason 3 for using Microsoft Copilot (binary 0/1)",
    "ai_why_copy_1": "Reason 1 for using Copy.ai (binary 0/1)", "ai_why_copy_2": "Reason 2 for using Copy.ai (binary 0/1)", "ai_why_copy_3": "Reason 3 for using Copy.ai (binary 0/1)",
    "ai_why_dalle_1": "Reason 1 for using DALL-E (binary 0/1)", "ai_why_dalle_2": "Reason 2 for using DALL-E (binary 0/1)", "ai_why_dalle_3": "Reason 3 for using DALL-E (binary 0/1)",
    "ai_why_deepseek_1": "Reason 1 for using DeepSeek (binary 0/1)", "ai_why_deepseek_2": "Reason 2 for using DeepSeek (binary 0/1)", "ai_why_deepseek_3": "Reason 3 for using DeepSeek (binary 0/1)",
    "ai_why_fake_1": "Reason 1 for using unrecognized/made-up AI tool name (quality-control item; binary 0/1)", "ai_why_fake_2": "Reason 2 for using unrecognized/made-up AI tool (binary 0/1)", "ai_why_fake_3": "Reason 3 for using unrecognized/made-up AI tool (binary 0/1)",
    "ai_why_gemini_1": "Reason 1 for using Google Gemini (binary 0/1)", "ai_why_gemini_2": "Reason 2 for using Google Gemini (binary 0/1)", "ai_why_gemini_3": "Reason 3 for using Google Gemini (binary 0/1)",
    "ai_why_genai_1": "Reason 1 for using generative AI tools generically (binary 0/1)", "ai_why_genai_2": "Reason 2 for using generative AI generically (binary 0/1)", "ai_why_genai_3": "Reason 3 for using generative AI generically (binary 0/1)",
    "ai_why_grok_1": "Reason 1 for using Grok (binary 0/1)", "ai_why_grok_2": "Reason 2 for using Grok (binary 0/1)", "ai_why_grok_3": "Reason 3 for using Grok (binary 0/1)",
    "ai_why_jasper_1": "Reason 1 for using Jasper AI (binary 0/1)", "ai_why_jasper_2": "Reason 2 for using Jasper AI (binary 0/1)", "ai_why_jasper_3": "Reason 3 for using Jasper AI (binary 0/1)",
    "ai_why_lechat_1": "Reason 1 for using Le Chat / Mistral (binary 0/1)", "ai_why_lechat_2": "Reason 2 for using Le Chat / Mistral (binary 0/1)", "ai_why_lechat_3": "Reason 3 for using Le Chat / Mistral (binary 0/1)",
    "ai_why_llama_1": "Reason 1 for using Llama / Meta AI (binary 0/1)", "ai_why_llama_2": "Reason 2 for using Llama / Meta AI (binary 0/1)", "ai_why_llama_3": "Reason 3 for using Llama / Meta AI (binary 0/1)",
    "ai_why_llm_1": "Reason 1 for using LLMs generically (binary 0/1)", "ai_why_llm_2": "Reason 2 for using LLMs generically (binary 0/1)", "ai_why_llm_3": "Reason 3 for using LLMs generically (binary 0/1)",
    "ai_why_midjourney_1": "Reason 1 for using Midjourney (binary 0/1)", "ai_why_midjourney_2": "Reason 2 for using Midjourney (binary 0/1)", "ai_why_midjourney_3": "Reason 3 for using Midjourney (binary 0/1)",
    "ai_why_perplexity_1": "Reason 1 for using Perplexity AI (binary 0/1)", "ai_why_perplexity_2": "Reason 2 for using Perplexity AI (binary 0/1)", "ai_why_perplexity_3": "Reason 3 for using Perplexity AI (binary 0/1)",
    "ai_why_qwen_1": "Reason 1 for using Qwen (binary 0/1)", "ai_why_qwen_2": "Reason 2 for using Qwen (binary 0/1)", "ai_why_qwen_3": "Reason 3 for using Qwen (binary 0/1)",
    "ai_why_writesonic_1": "Reason 1 for using Writesonic (binary 0/1)", "ai_why_writesonic_2": "Reason 2 for using Writesonic (binary 0/1)", "ai_why_writesonic_3": "Reason 3 for using Writesonic (binary 0/1)",

    # AI_HOW_TOOL_COLUMNS
    # How the respondent uses each named AI tool (binary 0/1; 5 use cases; NULL if tool not used)
    # Use cases: 1=writing/text generation, 2=finding information/research, 3=creative tasks,
    #            4=work/professional tasks, 5=other — confirm against questionnaire.
    "ai_how_ai_1": "Use case 1 for AI generally (binary 0/1)", "ai_how_ai_2": "Use case 2 for AI generally (binary 0/1)", "ai_how_ai_3": "Use case 3 for AI generally (binary 0/1)", "ai_how_ai_4": "Use case 4 for AI generally (binary 0/1)", "ai_how_ai_5": "Use case 5 for AI generally (binary 0/1)",
    "ai_how_anyword_1": "Use case 1 for Anyword (binary 0/1)", "ai_how_anyword_2": "Use case 2 for Anyword (binary 0/1)", "ai_how_anyword_3": "Use case 3 for Anyword (binary 0/1)", "ai_how_anyword_4": "Use case 4 for Anyword (binary 0/1)", "ai_how_anyword_5": "Use case 5 for Anyword (binary 0/1)",
    "ai_how_bard_1": "Use case 1 for Bard/Gemini (binary 0/1)", "ai_how_bard_2": "Use case 2 for Bard/Gemini (binary 0/1)", "ai_how_bard_3": "Use case 3 for Bard/Gemini (binary 0/1)", "ai_how_bard_4": "Use case 4 for Bard/Gemini (binary 0/1)", "ai_how_bard_5": "Use case 5 for Bard/Gemini (binary 0/1)",
    "ai_how_chatgpt_1": "Use case 1 for ChatGPT (binary 0/1)", "ai_how_chatgpt_2": "Use case 2 for ChatGPT (binary 0/1)", "ai_how_chatgpt_3": "Use case 3 for ChatGPT (binary 0/1)", "ai_how_chatgpt_4": "Use case 4 for ChatGPT (binary 0/1)", "ai_how_chatgpt_5": "Use case 5 for ChatGPT (binary 0/1)",
    "ai_how_claude_1": "Use case 1 for Claude (binary 0/1)", "ai_how_claude_2": "Use case 2 for Claude (binary 0/1)", "ai_how_claude_3": "Use case 3 for Claude (binary 0/1)", "ai_how_claude_4": "Use case 4 for Claude (binary 0/1)", "ai_how_claude_5": "Use case 5 for Claude (binary 0/1)",
    "ai_how_cohere_1": "Use case 1 for Cohere (binary 0/1)", "ai_how_cohere_2": "Use case 2 for Cohere (binary 0/1)", "ai_how_cohere_3": "Use case 3 for Cohere (binary 0/1)", "ai_how_cohere_4": "Use case 4 for Cohere (binary 0/1)", "ai_how_cohere_5": "Use case 5 for Cohere (binary 0/1)",
    "ai_how_copilot_1": "Use case 1 for Microsoft Copilot (binary 0/1)", "ai_how_copilot_2": "Use case 2 for Microsoft Copilot (binary 0/1)", "ai_how_copilot_3": "Use case 3 for Microsoft Copilot (binary 0/1)", "ai_how_copilot_4": "Use case 4 for Microsoft Copilot (binary 0/1)", "ai_how_copilot_5": "Use case 5 for Microsoft Copilot (binary 0/1)",
    "ai_how_copy_1": "Use case 1 for Copy.ai (binary 0/1)", "ai_how_copy_2": "Use case 2 for Copy.ai (binary 0/1)", "ai_how_copy_3": "Use case 3 for Copy.ai (binary 0/1)", "ai_how_copy_4": "Use case 4 for Copy.ai (binary 0/1)", "ai_how_copy_5": "Use case 5 for Copy.ai (binary 0/1)",
    "ai_how_dalle_1": "Use case 1 for DALL-E (binary 0/1)", "ai_how_dalle_2": "Use case 2 for DALL-E (binary 0/1)", "ai_how_dalle_3": "Use case 3 for DALL-E (binary 0/1)", "ai_how_dalle_4": "Use case 4 for DALL-E (binary 0/1)", "ai_how_dalle_5": "Use case 5 for DALL-E (binary 0/1)",
    "ai_how_deepseek_1": "Use case 1 for DeepSeek (binary 0/1)", "ai_how_deepseek_2": "Use case 2 for DeepSeek (binary 0/1)", "ai_how_deepseek_3": "Use case 3 for DeepSeek (binary 0/1)", "ai_how_deepseek_4": "Use case 4 for DeepSeek (binary 0/1)", "ai_how_deepseek_5": "Use case 5 for DeepSeek (binary 0/1)",
    "ai_how_fake_1": "Use case 1 for unrecognized/made-up AI tool name (QC item; binary 0/1)", "ai_how_fake_2": "Use case 2 for unrecognized/made-up AI tool (binary 0/1)", "ai_how_fake_3": "Use case 3 for unrecognized/made-up AI tool (binary 0/1)", "ai_how_fake_4": "Use case 4 for unrecognized/made-up AI tool (binary 0/1)", "ai_how_fake_5": "Use case 5 for unrecognized/made-up AI tool (binary 0/1)",
    "ai_how_gemini_1": "Use case 1 for Google Gemini (binary 0/1)", "ai_how_gemini_2": "Use case 2 for Google Gemini (binary 0/1)", "ai_how_gemini_3": "Use case 3 for Google Gemini (binary 0/1)", "ai_how_gemini_4": "Use case 4 for Google Gemini (binary 0/1)", "ai_how_gemini_5": "Use case 5 for Google Gemini (binary 0/1)",
    "ai_how_genai_1": "Use case 1 for generative AI generically (binary 0/1)", "ai_how_genai_2": "Use case 2 for generative AI generically (binary 0/1)", "ai_how_genai_3": "Use case 3 for generative AI generically (binary 0/1)", "ai_how_genai_4": "Use case 4 for generative AI generically (binary 0/1)", "ai_how_genai_5": "Use case 5 for generative AI generically (binary 0/1)",
    "ai_how_grok_1": "Use case 1 for Grok (binary 0/1)", "ai_how_grok_2": "Use case 2 for Grok (binary 0/1)", "ai_how_grok_3": "Use case 3 for Grok (binary 0/1)", "ai_how_grok_4": "Use case 4 for Grok (binary 0/1)", "ai_how_grok_5": "Use case 5 for Grok (binary 0/1)",
    "ai_how_jasper_1": "Use case 1 for Jasper AI (binary 0/1)", "ai_how_jasper_2": "Use case 2 for Jasper AI (binary 0/1)", "ai_how_jasper_3": "Use case 3 for Jasper AI (binary 0/1)", "ai_how_jasper_4": "Use case 4 for Jasper AI (binary 0/1)", "ai_how_jasper_5": "Use case 5 for Jasper AI (binary 0/1)",
    "ai_how_lechat_1": "Use case 1 for Le Chat / Mistral (binary 0/1)", "ai_how_lechat_2": "Use case 2 for Le Chat / Mistral (binary 0/1)", "ai_how_lechat_3": "Use case 3 for Le Chat / Mistral (binary 0/1)", "ai_how_lechat_4": "Use case 4 for Le Chat / Mistral (binary 0/1)", "ai_how_lechat_5": "Use case 5 for Le Chat / Mistral (binary 0/1)",
    "ai_how_llama_1": "Use case 1 for Llama / Meta AI (binary 0/1)", "ai_how_llama_2": "Use case 2 for Llama / Meta AI (binary 0/1)", "ai_how_llama_3": "Use case 3 for Llama / Meta AI (binary 0/1)", "ai_how_llama_4": "Use case 4 for Llama / Meta AI (binary 0/1)", "ai_how_llama_5": "Use case 5 for Llama / Meta AI (binary 0/1)",
    "ai_how_llm_1": "Use case 1 for LLMs generically (binary 0/1)", "ai_how_llm_2": "Use case 2 for LLMs generically (binary 0/1)", "ai_how_llm_3": "Use case 3 for LLMs generically (binary 0/1)", "ai_how_llm_4": "Use case 4 for LLMs generically (binary 0/1)", "ai_how_llm_5": "Use case 5 for LLMs generically (binary 0/1)",
    "ai_how_midjourney_1": "Use case 1 for Midjourney (binary 0/1)", "ai_how_midjourney_2": "Use case 2 for Midjourney (binary 0/1)", "ai_how_midjourney_3": "Use case 3 for Midjourney (binary 0/1)", "ai_how_midjourney_4": "Use case 4 for Midjourney (binary 0/1)", "ai_how_midjourney_5": "Use case 5 for Midjourney (binary 0/1)",
    "ai_how_perplexity_1": "Use case 1 for Perplexity AI (binary 0/1)", "ai_how_perplexity_2": "Use case 2 for Perplexity AI (binary 0/1)", "ai_how_perplexity_3": "Use case 3 for Perplexity AI (binary 0/1)", "ai_how_perplexity_4": "Use case 4 for Perplexity AI (binary 0/1)", "ai_how_perplexity_5": "Use case 5 for Perplexity AI (binary 0/1)",
    "ai_how_qwen_1": "Use case 1 for Qwen (binary 0/1)", "ai_how_qwen_2": "Use case 2 for Qwen (binary 0/1)", "ai_how_qwen_3": "Use case 3 for Qwen (binary 0/1)", "ai_how_qwen_4": "Use case 4 for Qwen (binary 0/1)", "ai_how_qwen_5": "Use case 5 for Qwen (binary 0/1)",
    "ai_how_writesonic_1": "Use case 1 for Writesonic (binary 0/1)", "ai_how_writesonic_2": "Use case 2 for Writesonic (binary 0/1)", "ai_how_writesonic_3": "Use case 3 for Writesonic (binary 0/1)", "ai_how_writesonic_4": "Use case 4 for Writesonic (binary 0/1)", "ai_how_writesonic_5": "Use case 5 for Writesonic (binary 0/1)",
}
